FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY etl/ ./etl/

ENTRYPOINT ["sh", "-c", "python etl/fetch_uv_data.py && python etl/fetch_cams_air_data.py"] 